# Generated by Django 6.0.1 on 2026-01-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('salary_min', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('skills', models.JSONField()),
                ('job_type', models.CharField(max_length=50)),
                ('posted_date', models.DateField()),
                ('match_score', models.IntegerField()),
            ],
        ),
    ]
